name: TEST-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./base_images/ -f ./base_images/alpine.dockerfile --tag my-image-name:$(date +%s)
